# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
pprint(mongo.list_database_names())

['admin',
 'classDB',
 'config',
 'epa',
 'local',
 'met',
 'petsitly_marketing',
 'travel_db',
 'uk_food']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene": {'$gt': 20}}

# Use count_documents to display the number of documents in the result
count = establishments.count_documents(query)

# Display the first document in the results using pprint
from pprint import pprint
first_doc = establishments.find_one(query)
pprint(first_doc)

{'AddressLine1': 'Skyline Hotel',
 'AddressLine2': 'Chelmsford Road',
 'AddressLine3': 'Barnston',
 'AddressLine4': 'Dunmow',
 'BusinessName': 'Inferno',
 'BusinessType': 'Takeaway/sandwich shop',
 'BusinessTypeID': 7844,
 'ChangesByServerID': 0,
 'Distance': 4650.02974294374,
 'FHRSID': 1349147,
 'LocalAuthorityBusinessID': '21/00036/COM',
 'LocalAuthorityCode': '122',
 'LocalAuthorityEmailAddress': 'environmentalhealth@uttlesford.gov.uk',
 'LocalAuthorityName': 'Uttlesford',
 'LocalAuthorityWebSite': 'http://www.uttlesford.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CM6 1LP',
 'RatingDate': '2022-01-27T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('672e80934518507e3d5b41df'),
 'geocode': {'latitude': 51.85643, 'longitude': 0.383023},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1349147',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 25, 'Structural': 20}}

In [7]:
# Convert the result to a Pandas DataFrame
new_df = pd.DataFrame(establishments.find(query))
# Display the number of rows in the DataFrame
print(f"Number of rows in the DataFrame: {len(new_df)}")
# Display the first 10 rows of the DataFrame
new_df.head(10)

Number of rows in the DataFrame: 7

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,672e80934518507e3d5b41df,1349147,0,21/00036/COM,Inferno,Takeaway/sandwich shop,7844,Skyline Hotel,Chelmsford Road,Barnston,...,http://www.uttlesford.gov.uk,environmentalhealth@uttlesford.gov.uk,"{'Hygiene': 25, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.383023, 'latitude': 51.85643}",,4650.029743,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
1,672e80944518507e3d5b4c1c,785554,0,08/00054/FOOD,Stratford News And Wines,Retailers - other,4613,107 Romford Road,Stratford,London,...,https://www.newham.gov.uk,food@newham.gov.uk,"{'Hygiene': 25, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.008382, 'latitude': 51.542772}",,4652.047527,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,672e80944518507e3d5b4dd1,514156,0,147,The Plough & Harrow,Pub/bar/nightclub,7843,,419 High Road Leytonstone,,...,http://www.walthamforest.gov.uk,environmentalhealth@walthamforest.gov.uk,"{'Hygiene': 25, 'Structural': 25, 'ConfidenceI...",FHRS,"{'longitude': 0.006434, 'latitude': 51.558138}",,4652.681025,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,672e80944518507e3d5b4de2,514651,0,47178,Chicks,Takeaway/sandwich shop,7844,,497 High Road,,...,http://www.walthamforest.gov.uk,environmentalhealth@walthamforest.gov.uk,"{'Hygiene': 25, 'Structural': 25, 'ConfidenceI...",FHRS,"{'longitude': 0.0071334, 'latitude': 51.5593505}",,4652.699935,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,672e80944518507e3d5b4e14,514221,0,17220,The Continental Food Exchange/TFC Leytonstone,Retailers - other,4613,,647-661 High Road Leytonstone,,...,http://www.walthamforest.gov.uk,environmentalhealth@walthamforest.gov.uk,"{'Hygiene': 25, 'Structural': 25, 'ConfidenceI...",FHRS,"{'longitude': 0.009602, 'latitude': 51.563902}",,4652.776654,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
5,672e80944518507e3d5b4e5e,552296,0,63877,O42,Restaurant/Cafe/Canteen,1,,885 High Road Leytonstone,,...,http://www.walthamforest.gov.uk,environmentalhealth@walthamforest.gov.uk,"{'Hygiene': 25, 'Structural': 25, 'ConfidenceI...",FHRS,"{'longitude': 0.014137, 'latitude': 51.570848}",,4652.865838,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
6,672e80944518507e3d5b4fda,1351355,0,348976,Busy Bees at Leytonstone,Caring Premises,5,Whipps Cross University Hospital,Whipps Cross Road,,...,http://www.walthamforest.gov.uk,environmentalhealth@walthamforest.gov.uk,"{'Hygiene': 25, 'Structural': 25, 'ConfidenceI...",FHRS,"{'longitude': 0.0034702, 'latitude': 51.5774342}",,4653.495442,True,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [8]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
ext_query = {"LocalAuthorityName": {"$regex": "London", "$options": "i"}, "RatingValue": {"$gte": 4}}

# Use count_documents to display the number of documents in the result
count = establishments.count_documents(ext_query)
print(count)
# Display the first document in the results using pprint
pprint(establishments.find_one(ext_query))

33
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('672e80934518507e3d5af57e'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [9]:
# Convert the result to a Pandas DataFrame
convert_results = establishments.find(ext_query)
convert_df = pd.DataFrame(convert_results)

# Display the number of rows in the DataFrame
print(f"Number of rows in the DataFrame: {len(convert_df)}")

# Display the first 10 rows of the DataFrame
convert_df.head(10)

Number of rows in the DataFrame: 33

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,672e80934518507e3d5af57e,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 0.508551, 'latitude': 51.369321}",,4627.439468,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,672e80934518507e3d5af8a5,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.249255999922752, 'latitude': 5...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,672e80934518507e3d5b03f2,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.561954, 'latitude': 51.543831}",,4631.968418,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,672e80934518507e3d5b11f2,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.346336990594864, 'latitude': 5...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,672e80934518507e3d5b11f3,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.346325, 'latitude': 51.464078}",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
5,672e80934518507e3d5b1900,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.287555, 'latitude': 51.504071}",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
6,672e80934518507e3d5b3a20,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.069286, 'latitude': 51.501121}",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
7,672e80934518507e3d5b3dce,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.048006, 'latitude': 51.503733}",,4649.173485,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,672e80934518507e3d5b3de8,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.047966, 'latitude': 51.504112}",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,672e80934518507e3d5b3dea,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0479655750095844, 'latitude': ...",,4649.188850,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

In [10]:
# Define the query for establishments in London with a RatingValue >= 4
query = {
    "RatingValue": {"$gte": 4},
    "LocalAuthorityName": {"$regex": "London", "$options": "i"} 
}

# Fetch the results from the database
establishments_in_london = list(establishments.find(query))

# Convert the result to a Pandas DataFrame
df_london_establishments = pd.DataFrame(establishments_in_london)

# Display the number of rows in the DataFrame
print(f"There are {df_london_establishments.shape[0]} establishments in London rating equal or greater than 4.")

There are 33 establishments in London rating equal or greater than 4.

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [11]:
# Define the location of the "Penang Flavours" restaurant
location_query = {"BusinessName": "Penang Flavours"}

# Retrieve latitude and longitude of "Penang Flavours"
penang_flavours = establishments.find_one(location_query, {"geocode.latitude": 1, "geocode.longitude": 1})

# Convert Decimal128 values to float using .to_decimal()
latitude = float(penang_flavours["geocode"]["latitude"])
longitude = float(penang_flavours["geocode"]["longitude"])

# Define the degree search range
degree_search = 0.01

# Build the query for establishments with RatingValue = 5 and within the search range of latitude/longitude
query = {
    "RatingValue": 5,
    "geocode.latitude": {"$gte": latitude - degree_search, "$lte": latitude + degree_search},
    "geocode.longitude": {"$gte": longitude - degree_search, "$lte": longitude + degree_search}
}
sort = "scores.Hygiene"
limit = 5
# Define the fields to return
fields = {'BusinessName': 1, 'scores': 1, 'geocode.latitude': 1, 'geocode.longitude': 1, 'RatingValue': 1}
# Get the count of documents that match the query
count = db.establishments.count_documents(query)
# Print the number of documents contained in the result
print("Number of matching documents:", count)
first_document = db.establishments.find_one(query)

# Display the first document in the results
print("First document in the results:")
pprint(first_document)

# Get the top 5 establishments that match the query and sort by hygiene score (decending)
top_5_establishments = list(db.establishments.find(query, fields).sort(sort, -1).limit(limit))

Number of matching documents: 87
First document in the results:
{'AddressLine1': '152 Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'TIWA N TIWA African Restaurant Ltd',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4646.930146257832,
 'FHRSID': 1069652,
 'LocalAuthorityBusinessID': 'PI/000206841',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1JQ',
 'RatingDate': '2020-10-24T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('672e80934518507e3d5b3370'),
 'geocode': {'latitude': 51.4870351, 'longitude': 0.0927429},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1069652',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}

In [12]:
# Convert result to Pandas DataFrame
df_top_5_nearby = pd.DataFrame(top_5_establishments)

# Print the top 5 results
df_top_5_nearby

,_id,BusinessName,RatingValue,scores,geocode
0,672e80934518507e3d5b3462,Lucky Food & Wine,5,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0910104, 'latitude': 51.4878934}"
1,672e80934518507e3d5b344d,Fineway Cash & Carry,5,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0909382, 'latitude': 51.4876089}"
2,672e80934518507e3d5b3484,Everest Stores Ltd,5,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0903232, 'latitude': 51.4876718}"
3,672e80934518507e3d5b347d,Premier Express,5,"{'Hygiene': 5, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0904552, 'latitude': 51.4877234}"
4,672e80934518507e3d5b3370,TIWA N TIWA African Restaurant Ltd,5,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0927429, 'latitude': 51.4870351}"

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [13]:
# Create a pipeline that:
# Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': 0}}
# Group by Local Authority from highest to lowest
group_query = {'$group': {"_id": "$LocalAuthorityName", "count": {"$sum": 1}}}
sort_values = {'$sort': { 'count': -1 }}

# Create pipeline
pipeline = [match_query, group_query, sort_values]

# Query the aggregation pipeline
agg_results = list(establishments.aggregate(pipeline))

# Print the number of documents in the result
print("Number of documents in the result:", len(agg_results))

# Print the first 10 results
pprint(agg_results[0:10])

Number of documents in the result: 55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [14]:
# Convert the result to a Pandas DataFrame
agg_result_df = pd.DataFrame(agg_results)
# Display the number of rows in the DataFrame
agg_count = len(agg_result_df)
print("Number of rows:", agg_count)

# Display the first 10 rows of the DataFrame
agg_result_df.head(10)

Number of rows: 55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542